"""Add ondelete CASCADE to foreign keys

Revision ID: 22cbc86da884
Revises: 333f171365e6
Create Date: 2026-07-05 03:46:02.235932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22cbc86da884'
down_revision: Union[str, Sequence[str], None] = '333f171365e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint(op.f('broadcasts_target_ward_id_fkey'), 'broadcasts', type_='foreignkey')
    op.create_foreign_key(None, 'broadcasts', 'location_boundaries', ['target_ward_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('chunks_document_id_fkey'), 'chunks', type_='foreignkey')
    op.create_foreign_key(None, 'chunks', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'document_summaries', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('embeddings_chunk_id_fkey'), 'embeddings', type_='foreignkey')
    op.create_foreign_key(None, 'embeddings', 'chunks', ['chunk_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('location_aliases_ward_id_fkey'), 'location_aliases', type_='foreignkey')
    op.create_foreign_key(None, 'location_aliases', 'location_boundaries', ['ward_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('queries_user_id_fkey'), 'queries', type_='foreignkey')
    op.create_foreign_key(None, 'queries', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('unanswered_queries_user_id_fkey'), 'unanswered_queries', type_='foreignkey')
    op.create_foreign_key(None, 'unanswered_queries', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unanswered_queries', type_='foreignkey')
    op.create_foreign_key(op.f('unanswered_queries_user_id_fkey'), 'unanswered_queries', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'queries', type_='foreignkey')
    op.create_foreign_key(op.f('queries_user_id_fkey'), 'queries', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'location_aliases', type_='foreignkey')
    op.create_foreign_key(op.f('location_aliases_ward_id_fkey'), 'location_aliases', 'location_boundaries', ['ward_id'], ['id'])
    op.drop_constraint(None, 'embeddings', type_='foreignkey')
    op.create_foreign_key(op.f('embeddings_chunk_id_fkey'), 'embeddings', 'chunks', ['chunk_id'], ['id'])
    op.drop_constraint(None, 'document_summaries', type_='foreignkey')
    op.drop_constraint(None, 'chunks', type_='foreignkey')
    op.create_foreign_key(op.f('chunks_document_id_fkey'), 'chunks', 'documents', ['document_id'], ['id'])
    op.drop_constraint(None, 'broadcasts', type_='foreignkey')
    op.create_foreign_key(op.f('broadcasts_target_ward_id_fkey'), 'broadcasts', 'location_boundaries', ['target_ward_id'], ['id'])

    # ### end Alembic commands ###
