"""add missing tenant models

Revision ID: 40f37b874b65
Revises: a0ca4fe9cfc9
Create Date: 2026-03-21 14:37:36.314822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '40f37b874b65'
down_revision: Union[str, Sequence[str], None] = 'a0ca4fe9cfc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_boundaries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('boundary', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # GeoAlchemy2 automatically creates the index
    # op.create_index('idx_location_boundaries_boundary', 'location_boundaries', ['boundary'], unique=False, postgresql_using='gist')
    
    op.create_table('broadcasts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('target_ward_id', sa.String(), nullable=True),
    sa.Column('total_sent', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['target_ward_id'], ['location_boundaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location_aliases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('ward_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ward_id'], ['location_boundaries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias')
    )
    op.create_table('unanswered_queries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unanswered_queries')
    op.drop_table('location_aliases')
    op.drop_table('broadcasts')
    # op.drop_index('idx_location_boundaries_boundary', table_name='location_boundaries', postgresql_using='gist')
    op.drop_table('location_boundaries')
    # ### end Alembic commands ###
