"""Add TenantIsolationMixin and robust doc columns

Revision ID: 76f392ca13b3
Revises: 789a2e4f1e35
Create Date: 2026-07-07 16:36:46.190502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76f392ca13b3'
down_revision: Union[str, Sequence[str], None] = '789a2e4f1e35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.add_column('broadcasts', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_broadcasts_tenant_id'), 'broadcasts', ['tenant_id'], unique=False)
    op.add_column('chunks', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_chunks_tenant_id'), 'chunks', ['tenant_id'], unique=False)
    op.add_column('communities', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_communities_tenant_id'), 'communities', ['tenant_id'], unique=False)
    op.add_column('conversations', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_conversations_tenant_id'), 'conversations', ['tenant_id'], unique=False)
    op.add_column('document_summaries', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_document_summaries_tenant_id'), 'document_summaries', ['tenant_id'], unique=False)
    op.add_column('documents', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.add_column('documents', sa.Column('allowed_roles', sa.JSON(), nullable=True))
    op.add_column('documents', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_documents_content_hash'), 'documents', ['content_hash'], unique=True)
    op.create_index(op.f('ix_documents_tenant_id'), 'documents', ['tenant_id'], unique=False)
    op.add_column('embeddings', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_embeddings_tenant_id'), 'embeddings', ['tenant_id'], unique=False)
    op.add_column('entities', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_entities_tenant_id'), 'entities', ['tenant_id'], unique=False)
    op.add_column('location_aliases', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_location_aliases_tenant_id'), 'location_aliases', ['tenant_id'], unique=False)
    op.add_column('location_boundaries', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_location_boundaries_tenant_id'), 'location_boundaries', ['tenant_id'], unique=False)
    op.add_column('queries', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_queries_tenant_id'), 'queries', ['tenant_id'], unique=False)
    op.add_column('relationships', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_relationships_tenant_id'), 'relationships', ['tenant_id'], unique=False)
    op.add_column('tenant_audit_logs', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_tenant_audit_logs_tenant_id'), 'tenant_audit_logs', ['tenant_id'], unique=False)
    op.add_column('unanswered_queries', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_unanswered_queries_tenant_id'), 'unanswered_queries', ['tenant_id'], unique=False)
    op.add_column('users', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_column('users', 'tenant_id')
    op.drop_index(op.f('ix_unanswered_queries_tenant_id'), table_name='unanswered_queries')
    op.drop_column('unanswered_queries', 'tenant_id')
    op.drop_index(op.f('ix_tenant_audit_logs_tenant_id'), table_name='tenant_audit_logs')
    op.drop_column('tenant_audit_logs', 'tenant_id')
    op.drop_index(op.f('ix_relationships_tenant_id'), table_name='relationships')
    op.drop_column('relationships', 'tenant_id')
    op.drop_index(op.f('ix_queries_tenant_id'), table_name='queries')
    op.drop_column('queries', 'tenant_id')
    op.drop_index(op.f('ix_location_boundaries_tenant_id'), table_name='location_boundaries')
    op.drop_column('location_boundaries', 'tenant_id')
    op.drop_index(op.f('ix_location_aliases_tenant_id'), table_name='location_aliases')
    op.drop_column('location_aliases', 'tenant_id')
    op.drop_index(op.f('ix_entities_tenant_id'), table_name='entities')
    op.drop_column('entities', 'tenant_id')
    op.drop_index(op.f('ix_embeddings_tenant_id'), table_name='embeddings')
    op.drop_column('embeddings', 'tenant_id')
    op.drop_index(op.f('ix_documents_tenant_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents')
    op.drop_column('documents', 'tenant_id')
    op.drop_column('documents', 'allowed_roles')
    op.drop_column('documents', 'content_hash')
    op.drop_index(op.f('ix_document_summaries_tenant_id'), table_name='document_summaries')
    op.drop_column('document_summaries', 'tenant_id')
    op.drop_index(op.f('ix_conversations_tenant_id'), table_name='conversations')
    op.drop_column('conversations', 'tenant_id')
    op.drop_index(op.f('ix_communities_tenant_id'), table_name='communities')
    op.drop_column('communities', 'tenant_id')
    op.drop_index(op.f('ix_chunks_tenant_id'), table_name='chunks')
    op.drop_column('chunks', 'tenant_id')
    op.drop_index(op.f('ix_broadcasts_tenant_id'), table_name='broadcasts')
    op.drop_column('broadcasts', 'tenant_id')
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    # sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    # )
    # ### end Alembic commands ###
