"""Add api_key to tenants

Revision ID: 016989620d64
Revises: 0d639a0e702d
Create Date: 2026-07-07 16:43:19.011411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '016989620d64'
down_revision: Union[str, Sequence[str], None] = '0d639a0e702d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('api_key', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_tenants_api_key'), 'tenants', ['api_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_api_key'), table_name='tenants')
    op.drop_column('tenants', 'api_key')
    # ### end Alembic commands ###
