"""Add platform audit logs and update models

Revision ID: 0d639a0e702d
Revises: bf029291e701
Create Date: 2026-07-05 05:11:31.141164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d639a0e702d'
down_revision: Union[str, Sequence[str], None] = 'bf029291e701'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=True),
    sa.Column('target_id', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_audit_logs_action'), 'platform_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_platform_audit_logs_actor_id'), 'platform_audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_platform_audit_logs_target_id'), 'platform_audit_logs', ['target_id'], unique=False)
    
    # Create enum type first
    tenant_status = sa.Enum('ACTIVE', 'SUSPENDED', 'CANCELLED', name='tenantstatus')
    tenant_status.create(op.get_bind(), checkfirst=True)
    
    op.add_column('tenants', sa.Column('status', tenant_status, server_default='ACTIVE', nullable=False))
    op.add_column('tenants', sa.Column('deletion_scheduled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tenants', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('tenants', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('tenants', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_column('tenants', 'updated_at')
    op.drop_column('tenants', 'created_at')
    op.drop_column('tenants', 'deletion_scheduled_at')
    op.drop_column('tenants', 'status')
    
    # Drop enum type
    tenant_status = sa.Enum('ACTIVE', 'SUSPENDED', 'CANCELLED', name='tenantstatus')
    tenant_status.drop(op.get_bind(), checkfirst=True)
    
    op.drop_index(op.f('ix_platform_audit_logs_target_id'), table_name='platform_audit_logs')
    op.drop_index(op.f('ix_platform_audit_logs_actor_id'), table_name='platform_audit_logs')
    op.drop_index(op.f('ix_platform_audit_logs_action'), table_name='platform_audit_logs')
    op.drop_table('platform_audit_logs')
    # ### end Alembic commands ###
