"""Add scopes and ips to tenants

Revision ID: 651de8cd108c
Revises: de479617b40f
Create Date: 2026-07-07 19:44:09.712798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '651de8cd108c'
down_revision: Union[str, Sequence[str], None] = 'de479617b40f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('allowed_scopes', postgresql.JSONB(astext_type=sa.Text()), server_default='["*"]', nullable=False))
    op.add_column('tenants', sa.Column('allowed_ips', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'allowed_ips')
    op.drop_column('tenants', 'allowed_scopes')
    # ### end Alembic commands ###
