"""Rename api_key to api_key_hash

Revision ID: de479617b40f
Revises: 016989620d64
Create Date: 2026-07-07 19:30:42.287457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de479617b40f'
down_revision: Union[str, Sequence[str], None] = '016989620d64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('api_key_hash', sa.String(length=255), nullable=True))
    op.drop_index(op.f('ix_tenants_api_key'), table_name='tenants')
    op.create_index(op.f('ix_tenants_api_key_hash'), 'tenants', ['api_key_hash'], unique=True)
    op.drop_column('tenants', 'api_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('api_key', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_tenants_api_key_hash'), table_name='tenants')
    op.create_index(op.f('ix_tenants_api_key'), 'tenants', ['api_key'], unique=True)
    op.drop_column('tenants', 'api_key_hash')
    # ### end Alembic commands ###
